name: PR bot GitHub APP

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled, review_requested, review_request_removed, assigned, unassigned, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Invoke PR-Bot (non-dependabot)
        uses: marqeta/pr-bot-cli@main
        if: github.actor != 'dependabot[bot]'
        with:
          github_token: ${{ secrets.PR_BOT_TOKEN }}

      - name: Invoke PR-Bot (dependabot)
        uses: marqeta/pr-bot-cli@main
        if: github.actor == 'dependabot[bot]'
        with:
          github_token: ${{ secrets.DEPENDABOT_GITHUB_TOKEN }}
