name: PR bot GitHub APP

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled, review_requested, review_request_removed, assigned, unassigned, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Invoke action
        uses: marqeta/pr-bot-cli@main
        with:
          github_token: ${{ secrets.PR_BOT_TOKEN }}
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.PR_BOT_TOKEN }}
