name: PR bot GitHub APP

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, review_requested, review_request_removed, assigned, unassigned, synchronize]

jobs:
  pr-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Invoke action
        uses: marqeta/pr-bot-cli@main
        with:
          github_token: ${{ secrets.PR_BOT_TOKEN }}
